// examples/preact/src/app.tsx
import { useEffect, useRef, useState } from "preact/hooks";
import { editable, plainSchema } from "edix";

export function App() {
  const ref = useRef<HTMLDivElement>(null);
  const [value, setValue] = useState(
    "Hello world.\nこんにちは。\n👍❤️🧑‍🧑‍🧒"
  );
  useEffect(() => {
    if (!ref.current) return;
    return editable(ref.current, {
      doc: value,
      schema: plainSchema({ multiline: true }),
      onChange: setValue,
    }).dispose;
  }, []);

  return (
    <div
      ref={ref}
      style={{
        backgroundColor: "white",
        border: "solid 1px darkgray",
        padding: 8,
      }}
    >
      {value.split("\n").map((t, i) => (
        <div key={i}>{t ? t : <br />}</div>
      ))}
    </div>
  );
}

// examples/qwik/src/app.tsx
import { component$, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import { editable, plainSchema } from "edix";

export const App = component$(() => {
  const value = useSignal("Hello world.\nこんにちは。\n👍❤️🧑‍🧑‍🧒");
  const ref = useSignal<HTMLDivElement>();

  useVisibleTask$(({ cleanup }) => {
    if (!ref.value) return;
    const editor = editable(ref.value, {
      doc: value.value,
      schema: plainSchema({ multiline: true }),
      onChange: (v) => {
        value.value = v;
      },
    });
    cleanup(() => {
      editor.dispose();
    });
  });

  return (
    <div
      ref={ref}
      style={{
        backgroundColor: "white",
        border: "solid 1px darkgray",
        padding: 8,
      }}
    >
      {value.value.split("\n").map((t, i) => (
        <div key={i}>{t ? t : <br />}</div>
      ))}
    </div>
  );
});
