// examples/svelte/src/App.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { editable, plainSchema, type EditableHandle } from "edix";

  let value = $state("Hello world.\nこんにちは。\n👍❤️🧑‍🧑‍🧒");
  let ref: HTMLElement | undefined = $state();
  let editor: EditableHandle | null = null;
  onMount(() => {
    editor = editable(ref!, {
      schema: plainSchema({ multiline: true }),
      onChange: (v) => {
        value = v;
      },
    });
  });
  onDestroy(() => {
    editor?.dispose();
  });
</script>

<div bind:this={ref} class="editor">
  {#each value.split("\n") as t, i (i)}
    <div>
      {#if t}
        {t}
      {:else}
        <br />
      {/if}
    </div>
  {/each}
</div>

<style>
  .editor {
    background-color: white;
    border: solid 1px darkgray;
    padding: 8px;
  }
</style>

// examples/solid/src/App.tsx
import { createMemo, createSignal, For, onCleanup, onMount } from "solid-js";
import { editable, plainSchema } from "edix";

function App() {
  let ref: HTMLDivElement | undefined;
  const [value, setValue] = createSignal(
    "Hello world.\nこんにちは。\n👍❤️🧑‍🧑‍🧒"
  );
  onMount(() => {
    const editor = editable(ref!, {
      schema: plainSchema({ multiline: true }),
      onChange: setValue,
    });
    onCleanup(() => {
      editor.dispose();
    });
  });

  return (
    <div
      ref={ref}
      style={{
        "background-color": "white",
        border: "solid 1px darkgray",
        padding: "8px",
      }}
    >
      <For each={createMemo(() => value().split("\n"))()}>
        {(t) => <div>{t ? t : <br />}</div>}
      </For>
    </div>
  );
}

export default App;
