// examples/vue/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { createEditor, plainSchema } from "edix";

const value = ref("Hello world.\nこんにちは。\n👍❤️🧑‍🧑‍🧒")
const element = ref<HTMLDivElement>()
let cleanup: (() => void) | null = null
onMounted(() => {
  cleanup = createEditor({
    doc: value.value,
    schema: plainSchema({ multiline: true }),
    onChange: (v) => {
      value.value = v
    },
  }).input(element.value!)
})
onUnmounted(() => {
  cleanup?.()
})
</script>

<template>
  <div ref="element" class="editor">
    <div v-for="(t, i) in value.split('\n')">
      <span :key="i" v-if="t">{{ t }}</span>
      <br v-else />
    </div>
  </div>
</template>

<style scoped>
.editor {
  background-color: white;
  border: solid 1px darkgray;
  padding: 8px;
}
</style>

// examples/svelte/src/App.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { createEditor, plainSchema, type Editor } from "edix";

  let value = $state("Hello world.\nこんにちは。\n👍❤️🧑‍🧑‍🧒");
  let ref: HTMLElement | undefined = $state();
  let cleanup: (() => void) | null = null;
  onMount(() => {
    cleanup = createEditor({
      doc: value,
      schema: plainSchema({ multiline: true }),
      onChange: (v) => {
        value = v;
      },
    }).input(ref!);
  });
  onDestroy(() => {
    cleanup?.();
  });
</script>

<div bind:this={ref} class="editor">
  {#each value.split("\n") as t, i (i)}
    <div>
      {#if t}
        {t}
      {:else}
        <br />
      {/if}
    </div>
  {/each}
</div>

<style>
  .editor {
    background-color: white;
    border: solid 1px darkgray;
    padding: 8px;
  }
</style>
